'use client'
import { useEffect, useState } from 'react';
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import StopLight from '@/components/StopLight'

export default function Home() {

  const [firstLightColor, setFirstLightColor] = useState('red');
  const [secondLightColor, setSecondLightColor] = useState('red'); 
  const [counter, setCounter] = useState(0);

  const runLightChange = () => {
    switch (counter) {
      case 0: {
        setFirstLightColor(() => 'red')
        setSecondLightColor(() => 'red')
      }
      break;
      case 1: {
        setFirstLightColor(() => 'green')
        setSecondLightColor(() => 'red')
      }
      break;
      case 2: {
        setFirstLightColor(() => 'yellow')
        setSecondLightColor(() => 'red')
      }
      break;
      case 3: {
        setFirstLightColor(() => 'red')
        setSecondLightColor(() => 'red')
      }
      break;
      case 4: {
        setFirstLightColor(() => 'red')
        setSecondLightColor(() => 'green')
      }
      break;
      case 5: {
        setFirstLightColor(() => 'red')
        setSecondLightColor(() => 'yellow')
      }
      break;
      default: {
       
      }
    }
    const newCounter = counter + 1 === 6 ? 0 : counter + 1

    setCounter(() => newCounter);
  }

  return (
    <>
      <Head>
        <title>StopLight</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`} onClick={runLightChange}>
        <div className={styles.firstLightContainer}>
          <StopLight color={firstLightColor}/>
        </div>

        <div className={styles.secondLightContainer}>
          <StopLight color={secondLightColor} />
        </div>

      </main>
    </>
  )
}
